### ISSUE TITLE
Reading junk data

### ISSUE THREAD

**Issue by deepakkarki** [Apaar/PRU-Bridge#1]
"Read :Read currently returns a single character without any checks on whether there is any data in the channel or not"
Can you think of a possible solution for this? The developer would not want to just keep on reading the "data" even if there isn't any.

**Comment by Apaar** [comment]
In the control channel there is a pru_data array it will incremented everytime a write takes place and decremented if it is non zero ie there is data to read.I was thinking of using this to check for data but am still looking for a way to send a meaningful error message back via sysfs.

**Comment by Apaar** [comment]
Just pushed updated driver with checks implemented ,right now i return -1 if there is no data to read
